### ISSUE TITLE
resolver fetches all attributes regardless the query

### ISSUE THREAD

**Issue by teekey99** [mickhansen/graphql-sequelize#555] opened 2017-12-20 17:46 UTC
According to this package readme, `resolver` should automatically fetch only those model attributes, that are defined in GraphQL query. However, in my case the resolver always fetches ALL model attributes regardless the query defined. Everything else works just fine, I get the data I need, only the query sent to DB is still getting unnecessary fields too.

Model:
```javascript
// @flow
import type { DataTypes, Sequelize } from './types';
import type { UserModel } from './types/user';

export default (Sequelize: Sequelize, DataTypes: DataTypes): UserModel => {
  const User: UserModel = Sequelize.define(
    'User',
    {
      id: {
        type: DataTypes.INTEGER(11),
        allowNull: false,
        primaryKey: true,
        autoIncrement: true,
      },
      email: {
        type: DataTypes.STRING(60),
        allowNull: false,
        unique: true,
      },
      password: {
        type: DataTypes.STRING(60),
        allowNull: true,
      },
      date_registered: {
        type: DataTypes.DATE,
        allowNull: true,
      },
      date_last_activity: {
        type: DataTypes.DATE,
        allowNull: true,
      },
      profile_name: {
        type: DataTypes.STRING(100),
        allowNull: false,
      },
      profile_birth: {
        type: DataTypes.DATEONLY,
        allowNull: true,
      },
      profile_picture: {
        type: DataTypes.STRING(200),
        allowNull: true,
      },
      activation_key: {
        type: DataTypes.STRING(60),
        allowNull: true,
      },
      facebook_connect: {
        type: DataTypes.BOOLEAN,
        allowNull: false,
      },
      activated: {
        type: DataTypes.BOOLEAN,
        allowNull: false,
      },
      blocked: {
        type: DataTypes.BOOLEAN,
        allowNull: false,
      },
      preregistered: {
        type: DataTypes.BOOLEAN,
        allowNull: false,
      },
      merge_hash: {
        type: DataTypes.STRING(65),
        allowNull: false,
      },
      synchronized_with_sendgrid: {
        type: DataTypes.BOOLEAN,
        allowNull: false,
      },
      date_edited: {
        type: DataTypes.DATE,
        allowNull: false,
      },
      private_key: {
        type: DataTypes.STRING(32),
        allowNull: true,
        unique: true,
      },
      registration_source: {
        type: DataTypes.INTEGER(11),
        allowNull: false,
      },
    },
    {
      tableName: 'user',
      timestamps: false,
    },
  );

  return User;
};
```
GraphQL type definition:
```javascript
// @flow
import { attributeFields } from 'graphql-sequelize';
import { GraphQLObjectType, GraphQLInt, GraphQLNonNull } from 'graphql';

import models from 'models';
import nodeInterface, { nodeTypeMapper } from 'schema/nodeInterface';

import type { UserAttributes, UserModel } from 'models/types/user';

const User: UserModel = models.User;

const UserType = new GraphQLObjectType({
  name: User.name,
  description: 'SizeID User',
  fields: () => ({
    user_id: {
      type: new GraphQLNonNull(GraphQLInt),
      resolve: (user: UserAttributes) => user.id,
    },
    ...attributeFields(User, {
      exclude: ['id'],
      globalId: true,
    }),
  }),
  interfaces: [nodeInterface],
});

nodeTypeMapper.mapTypes({
  [User.name]: UserType,
});

export default UserType;
```
GraphQL query definition:
```javascript
// @flow
import { GraphQLList } from 'graphql';
import { defaultListArgs, resolver } from 'graphql-sequelize';

import models from 'models';
import { UserType } from 'schema/types';

export default {
  type: new GraphQLList(UserType),
  name: 'User_UsersQuery',
  args: {
    ...defaultListArgs(),
  },
  resolve: resolver(models.User),
};
```
GraphQL schema definition:
```javascript
import { GraphQLSchema, GraphQLObjectType } from 'graphql';

import queries from './queries';
import { nodeField } from './nodeInterface';

export default new GraphQLSchema({
  query: new GraphQLObjectType({
    name: 'Query',
    fields: () => ({
      ...queries,
      node: nodeField,
    }),
  }),
});
```
Am I missing something? As I said, everything works fine (sorting, filtering, limits etc.), I can define my queries inside my React components without any issue, Relay gets only the data defined in the query, but I can see in the console that the server is still fetching unnecessary data too. Thanks for any suggestion!

**Comment by intellix** [comment] 2017-12-20 18:19
Dupe of https://github.com/mickhansen/graphql-sequelize/issues/295

**Comment by teekey99** [comment] 2017-12-20 19:05
@intellix That issue states it happens while using `node` query only. I am having the issue with other queries too. Anyway, I can see  @mickhansen wrote `filterAttributes` would be dropped in future versions of `graphql-sequelize`. If that happened, why the readme still states `resolver` is able to filter attributes according to query?

**Closed** 2017-12-20 19:49 UTC

**Comment by mickhansen** [comment] 2017-12-21 09:31
@teekey99 Because currently it is able to, if you use the option

**Comment by teekey99** [comment] 2017-12-21 09:41
@mickhansen Thank you for your response! If I understand it correctly, it happens, when I specify the attributes in `before` as `options.attributes`, but it does not happen out of the box?

**Comment by teekey99** [comment] 2017-12-21 10:09
@mickhansen No problem! Thank you for answering, I understand those issues with caching / batching and I think it's much better when developers implement their own logic in this. I was just confused about the readme saying that `resolver`:

> Only loads the attributes defined in the query

I always prefer not to implement something that is already present in some third-party library and working.

**Comment by mickhansen** [comment] 2017-12-21 10:16
Yeah the docs need an update it looks like.
