### ISSUE TITLE
"TypeError: source.get is not a function" Occurs when I this.props.relay.forceFetch on a connection

### ISSUE THREAD

**Issue by rgovindji** [mickhansen/graphql-sequelize#227] opened 2016-05-05 19:27 UTC
Trying to update a listview but whenever I call this.props.relay.forceFetch() I get a server request failed due to source.get not being a function.

Using the following packages:
+-- express-graphql@0.5.1
+-- graphql@0.5.0
+-- graphql-relay@0.4.1
+-- graphql-sequelize@1.1.1

**Comment by mickhansen** [comment] 2016-05-05 20:13
Please provide a stack trace and a SSCCE of some sort. Your models, query, connections etc, something i can copy/paste and run because the info you've given doesn't help me to help you i'm afraid :)

**Comment by rgovindji** [comment] 2016-05-05 21:05
Sorry, I have provided more details below.

The issue occurs in resolver.js. Stepping through I found that 'source' is a GraphQLObjectType with the following attributes
name = "User"
description = "This represents a user"
typeOf = undefined

But on initial fetch of the data I see that 'source' is an instance of User with attributes
$modelOptions
$options
dataValues
invites

stack trace:

```
TypeError: source.get is not a function
    at resolver (/GraphQLApp/node_modules/graphql-sequelize/lib/resolver.js:84:31)
    at resolver (/GraphQLApp/node_modules/graphql-sequelize/lib/relay.js:358:14)
    at resolveOrError (/GraphQLApp/node_modules/graphql/execution/execute.js:457:12)
    at resolveField (/GraphQLApp/node_modules/graphql/execution/execute.js:448:16)
    at /GraphQLApp/node_modules/graphql/execution/execute.js:256:18
    at Array.reduce (native)
    at executeFields (/GraphQLApp/node_modules/graphql/execution/execute.js:254:50)
    at completeObjectValue (/GraphQLApp/node_modules/graphql/execution/execute.js:648:10)
    at completeAbstractValue (/GraphQLApp/node_modules/graphql/execution/execute.js:624:10)
    at completeValue (/GraphQLApp/node_modules/graphql/execution/execute.js:566:12)
    at /GraphQLApp/node_modules/graphql/execution/execute.js:524:14
    at run (/GraphQLApp/node_modules/babel-cli/node_modules/core-js/modules/es6.promise.js:89:22)
    at /GraphQLApp/node_modules/babel-cli/node_modules/core-js/modules/es6.promise.js:102:28
    at flush (/GraphQLApp/node_modules/babel-cli/node_modules/core-js/modules/_microtask.js:18:9)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickDomainCallback (internal/process/next_tick.js:122:9)
```

Here is the connection I am trying to force fetch.

```
const userInviteConnection = relay.sequelizeConnection({
  name: 'userInvite',
  nodeType: Invite,
  target: Conn.models.profile.Invites,  // In my db.js I have Profile.Invites = Profile.hasMany(Invite, {as: 'invites', singular: 'invite'});
  orderBy: new GraphQLEnumType({
    name: User.name + Invite.name + 'ConnectionOrder',
    values: {
      ID: {value: [Conn.models.invite.primaryKeyAttribute, 'ASC']},
      LATEST: {value: ['updatedAt', 'DESC']},
      STATUS: {value: ['status', 'ASC']},
    }
  }),
  where: function (key, value) {
    // for custom args other than connectionArgs return a sequelize where parameter
    return {[key]: value};
  },
  connectionFields: () => ({
    totalCount: {
      type: GraphQLInt,
      resolve: function (connection, args, context) {
        return connection.source.countInvites({
          where: connection.where
        });
      }
    },
    getParticipating: {
      type: GraphQLBoolean,
      resolve: (edge) => {
        /*
         * We attach the connection source to edges
         */
        return edge.node.status === PARTICIPANT;
      }
    }
  }
  )
});
```

User & Invite Schema

```
const User = new GraphQLObjectType({
  name: 'User',
  description: 'This represents a user',
  fields: () => {
    return {
      id: globalIdField('User'),
      userName: {
        type: GraphQLString
      },
      email: {
        type: GraphQLString
      },
      invites: {
        type: userInviteConnection.connectionType,
        args: {
          ...userInviteConnection.connectionArgs,
          status: {
            type: inviteStatusEnum
          }
        },
        resolve: userInviteConnection.resolve
      },
  interfaces: [nodeInterface]
});

const Invite = new GraphQLObjectType({
  name: 'Invite',
  description: 'This represents a user invite',
  fields: () => {
    return {
      id: globalIdField('Invite'),
      user: {
        type: User,
        resolve: resolver(Conn.models.invite.Profile)
      },
      status: {
        args: {
          status: {
            type: GraphQLString
          },
        },
        type: inviteStatusEnum
      },
      createdAt: {
        type: GraphQLString
      },
      inviteMessage: {
        type: GraphQLString
      }
    }
  },
  interfaces: [nodeInterface]
});
```

**Comment by rgovindji** [comment] 2016-05-06 15:39
@mickhansen Would my issue be related to this https://github.com/mickhansen/graphql-sequelize/issues/30 ?

**Comment by mickhansen** [comment] 2016-05-06 15:41
I have no idea exactly what causes your issue.
If you want this fixed in a timely manner please provide a full SSCCE, i don't have the time currently to try and reproduce your case and i can't immediately see what the issue is.

**Comment by rgovindji** [comment] 2016-05-06 20:56
Alright let me try to organize some sample code that will reproduce this issue. I will get back to you soon.

**Comment by rgovindji** [comment] 2016-05-07 16:48
Small update I managed to get a bit further. I determined that one issue is in my User schema I have  id: globalIdField('User') but it should have been  id: globalIdField(Conn.models.profile.name). This was causing this code to never find my profile model:

```
case 10:
          model = _Object$keys(sequelize.models).find(function (model) {
            return model === type;
          });
          return context$2$0.abrupt('return', model ? sequelize.models[model].findById(id) : nodeType ? nodeType.type : null);
```


My issue now is I am receiving  a new error: `Could not determine runtime type of value "[object SequelizeInstance:profile]" for field Query.node.`

**Comment by mickhansen** [comment] 2016-05-07 16:54
Are you using mapTypes with the node type mapper we provide?

**Comment by rgovindji** [comment] 2016-05-07 16:58
It works! Yes that was the final issue, I made the change just before you commented.

Since my Graphql models had different names than my Sequelize models it was messing everything up.

This fixed it:
```
nodeTypeMapper.mapTypes({
  [**Conn.models.profile.name**]: User,
```

**Comment by mickhansen** [comment] 2016-05-07 17:02
Yeah it's definitely helpfull to use camelcase model names with the `tableName` option for snake_case table names and then have pretty much 1:1 model names to type names.

You can also do without but you need a customer node resolver/type mapper in that case.

**Closed by mickhansen** 2016-05-07 17:02 UTC

**Comment by rgovindji** [comment] 2016-05-25 15:36
Hi @mickhansen I ran into a similar issue with Relay connections and after adding the connection name plus the edgeType it seems to have resolved it. Just making sure what I did was correct as I didn't see this in the Relay connections example.

```
nodeTypeMapper.mapTypes({
  [Conn.models.profile.name]: User,
  [Conn.models.invite.name]: Invite,
  ['userInvite']: userInviteConnection.edgeType
});
```

**Comment by mickhansen** [comment] 2016-05-25 16:52
@rgovindji edges should never be resolved individually by relay as far as i know

**Comment by rgovindji** [comment] 2016-05-25 17:21
Ahh I am still trying to grok relay. I am trying to do a RANGE_ADD mutation and I return the connection edge in the response. Maybe I'm not supposed to do that but I thought it was necessary to get optimistic updates to work.

**Comment by mickhansen** [comment] 2016-05-26 04:18
@rgovindji You should definitely return an edge to a mutation that adds a connection item. However that specific item would never be looked up in a node() query which the nodeTypeMapper is for
