### ISSUE TITLE
Attributes renamed through the 'map' option of attributeFields never get queried

### ISSUE THREAD

**Issue by fastfedora** [mickhansen/graphql-sequelize#276] opened 2016-07-11 22:05 UTC
If you use the `map` option of `attributeFields` to rename fields, the fields are filtered out and never queried.

The problem appears to be in `src\resolver.js` in the block processing `option.filterAttributes`. The raw attribute names from the Sequelize model are always used to determine what attributes to include in the query, instead of the attribute names for the GraphQL type. This happens regardless of whether `filterAttributes` is set to true or false.

One solution might be to pass a `mapAttributeName` function in `options` to `resolverFactory` that can do the name translation before filtering the attributes. This would be the reverse of the `map` function passed into `attributeFields`.

For now I'm going to investigate field renaming at the Sequelize model level, since we're already abstracted out model and query generation into a library, so switching the level at which renaming occurs should be easy. (We're using underscores for database field names and camelCase for GraphQL attribute names).

**Comment by mickhansen** [comment] 2016-07-12 07:55
You can also disable filterAttributes, i'll likely remove the option globally in the next major when we switch the codebase to use batching.

**Comment by fastfedora** [comment] 2016-07-12 19:51
I don't think disabling filtering by setting `filterAttributes` to false will work, since that just causes the full list of raw attribute names to be used to determine the query. ([see here](https://github.com/mickhansen/graphql-sequelize/blob/4c8b4955c897b9f12c1bc45d5f0f3123f219a18a/src/resolver.js#L81)).

I solved the problem by pushing the renaming down to the Sequelize layer, so my model field names now match my GraphQL attribute names, both of which use camelCase and only my SQL column names use snake_case. I removed all references to the `map` function, so now everything works for me. Others using the `map` function may still run into this issue.

**Comment by majodev** [comment] 2017-01-21 12:51
Any progress on this? Seems like resolving renamed fields is still broken in v4.0.0.

**Comment by mickhansen** [comment] 2017-01-23 07:55
@majodev Fraid not, actually thought we had removed filterAttributes in v4

**Comment by kesemdavid** [comment] 2017-08-16 11:04
@mickhansen +1 to this issue, anything changed since the last comment?

**Comment by rcknr** [comment] 2017-10-25 06:58
What's the status of this? It looks like it makes renaming fields through map option pretty useless. Is there a known workaround or fix planned for this?

**Comment by mickhansen** [comment] 2017-10-25 07:13
@rcknr is the issue still present with attribute filtering disabled (which i think it is by default these days)?

**Comment by rcknr** [comment] 2017-10-25 07:54
@mickhansen I don't use it, so don't have it either enabled or disabled. I'm following [the example given in docs](https://github.com/mickhansen/graphql-sequelize#resolve-helpers) but in my case Sequelize model fields are remapped like so: `map: field => _.camelCase(field)`.
I'm getting null values for any field renamed with this map function. When I remove mapping it works fine.

**Comment by mickhansen** [comment] 2017-10-25 08:29
@rcknr Sounds like it's definitely broken then. I don't have any immediate fix planned.
I reckon the problem is that the built in resolver for graphql fields will no longer be able to find a value matching it's own name.

**Comment by rcknr** [comment] 2017-10-25 08:31
@mickhansen any advice what can be done? Can I use "after" callback of resolver to remap keys?

**Comment by mickhansen** [comment] 2017-10-25 08:40
`before` and then modifying `attributes` to alias the keys to the expected mappings might work

**Comment by rcknr** [comment] 2017-10-25 09:08
@mickhansen the problem is not getting the data from Sequelize: as you pass a Sequelize model as a parameter for resolver it queries for snake cased attributes and return data correctly. The problem is to map data from Sequelize to GraphQL type fields which a renamed using map option.

**Comment by mickhansen** [comment] 2017-10-25 09:18
@rcknr It's not exactly returning data correctly as the keys don't map to remapped fields, and the built-in graphql resolver will look for a key match - So either you change the resolver on the field or you change the keys returned.

**Comment by rcknr** [comment] 2017-10-25 09:29
@mickhansen The following workaround works for me. This is inside type definition:
Before:
```
fields: attributeFields(Profile, {
    globalId: true,
    map: field => _.camelCase(field)
})
```
After:
```
fields: _.each(attributeFields(Profile, {
    globalId: true,
    map: field => _.camelCase(field)
}), (val, key) => {
    val.resolve = (object) => object[_.snakeCase(key)]
})
```
So this could be done inside of `attributeFields` or at least documented.

**Comment by mickhansen** [comment] 2017-10-25 09:55
@rcknr sounds like a reasonable solution

**Comment by abimelex** [comment] 2017-12-21 10:46
Thanks @rcknr it pointed me to the correct solution. Since I couldn't use `id` as a key, because it's reserved keyword in relay I needed to map it. My solution for a single key map looks like this:

```
const userFields = attributeFields(db.bankAccount, {map: {id: 'userId'}});
userFields.userId.resolve = (object) => { return object.id; };

const userType = new GraphQLObjectType({
    name: 'User',
    fields: userFields
});
```

**Closed** 2020-04-30 16:38 UTC
Labels: wontfix
